# Generated by Django 4.0.1 on 2022-01-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('descripcion', models.CharField(max_length=55)),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='titulos.entrega')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='titulos.titulo')),
            ],
        ),
    ]
