# Generated by Django 4.0.1 on 2022-01-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_franquicia', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('genero', models.ManyToManyField(blank=True, related_name='franquicia', to='tags.Genero')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_staff', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulo', models.CharField(max_length=255)),
                ('publicacion', models.DateField(blank=True, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Emision', 'Emision'), ('Proximamente', 'Proximamente')], max_length=50)),
                ('formato', models.CharField(choices=[('Anime', 'Anime'), ('manga', 'Manga'), ('pelicula', 'Pelicula'), ('TVshow', 'Tvshow'), ('serie', 'Serie')], max_length=50)),
                ('imagen1', models.URLField(blank=True, null=True)),
                ('imagen2', models.URLField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('clip', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('franquicia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='titulos.franquicia')),
                ('genero', models.ManyToManyField(blank=True, related_name='titulos', to='tags.Genero')),
                ('staff', models.ManyToManyField(blank=True, related_name='staff', to='titulos.Staff')),
            ],
            options={
                'ordering': ['franquicia', 'publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('titulo_interprete1', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_interprete2', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo_interprete3', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('obra', models.ManyToManyField(blank=True, related_name='personajes', to='titulos.Titulo')),
                ('selec_interprete1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personajes1', to='titulos.staff')),
                ('selec_interprete2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personajes2', to='titulos.staff')),
                ('selec_interprete3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personajes3', to='titulos.staff')),
            ],
            options={
                'ordering': ['obra__nombre_titulo'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre_entrega', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='titulos.titulo')),
            ],
            options={
                'ordering': ['titulo', 'numero'],
            },
        ),
    ]
