# Generated by Django 4.0.1 on 2022-01-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_franquicia', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre_genero'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulo', models.CharField(max_length=255)),
                ('publicacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Emision', 'Emision'), ('Proximamente', 'Proximamente')], max_length=50)),
                ('formato', models.CharField(choices=[('Anime', 'Anime'), ('manga', 'Manga'), ('película', 'Pelicula'), ('TVshow', 'Tvshow'), ('serie', 'Serie')], max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('franquicia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='titulos.franquicia')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_staff', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='titulos.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('interprete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaje', to='titulos.staff')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personaje', to='titulos.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='LinksEntregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='titulos.titulo')),
            ],
        ),
        migrations.AddField(
            model_name='franquicia',
            name='genero',
            field=models.ManyToManyField(blank=True, related_name='franquicia', to='titulos.Genero'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre_entrega', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='titulos.titulo')),
            ],
        ),
    ]
