# Generated by Django 4.0.1 on 2022-01-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['titulo', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='franquicia',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='personaje',
            options={'ordering': ['obra__nombre_titulo']},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'ordering': ['franquicia', 'publicacion']},
        ),
        migrations.AddField(
            model_name='titulo',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
