# Generated by Django 4.0.1 on 2022-01-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linksentregas',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='titulos.entrega'),
        ),
    ]
