# Generated by Django 4.0.1 on 2022-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0002_alter_entrega_numero_alter_linksentregas_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franquicia',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='clip',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='imagen1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='imagen2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
